import type {
  Category,
  ProductionPlan,
  Preferences,
  Product,
  ProductionBatch,
  StockMovement,
  UserRole,
} from "@/lib/types";

const now = new Date("2026-04-15T09:40:54+08:00");

export const defaultPreferences: Preferences = {
  rowsPerPage: 10,
};

export const defaultRole: UserRole = "owner";

export const defaultLastSyncedAt = new Date(
  now.getTime() - 12 * 60 * 1000,
).toISOString();

export const defaultCategories: Category[] = [
  { id: "cat-1", name: "VALENTINE'S DAY EDITION", order: 0, createdAt: defaultLastSyncedAt },
  { id: "cat-2", name: "RAMADHAN EDITION", order: 1, createdAt: defaultLastSyncedAt },
  { id: "cat-3", name: "LUNAR NEW YEAR EDITION", order: 2, createdAt: defaultLastSyncedAt },
  { id: "cat-4", name: "GALAXY COLLECTION", order: 3, createdAt: defaultLastSyncedAt },
  { id: "cat-5", name: "CLASSIC ESSENTIALS", order: 4, createdAt: defaultLastSyncedAt }
];

export const defaultProducts: Product[] = [
  {
    id: "prd-1",
    sku: "VAL-GEM-4ER-G",
    name: "4EVER Bracelet | Gold | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "4V",
    currentStock: { indira: 2, mita: 0, warehouse: 17 },
    lowStockThreshold: 7,
    velocity30d: 1.2,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 9.9,
    consignmentPriceIdr: 370000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-2",
    sku: "VAL-GEM-4ER-S",
    name: "4EVER Bracelet | Silver | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "4S",
    currentStock: { indira: 0, mita: 0, warehouse: 11 },
    lowStockThreshold: 5,
    velocity30d: 0.4,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 8.8,
    consignmentPriceIdr: 342000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-3",
    sku: "VAL-GEM-B-G",
    name: "BABE Bracelet | Gold | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "BB",
    currentStock: { indira: 0, mita: 0, warehouse: 10 },
    lowStockThreshold: 5,
    velocity30d: 0.9,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 8.6,
    consignmentPriceIdr: 335000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-4",
    sku: "VAL-GEM-B-S",
    name: "BABE Bracelet | Silver | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "BS",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 5,
    velocity30d: 1.7,
    wholesaleActive: true,
    consignmentActive: false,
    wholesalePriceEur: 9.4,
    consignmentPriceIdr: 365000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-5",
    sku: "RE-GEM-EM-G",
    name: "Eid Mubarak Bracelet | Gold | Ramadhan Edition",
    categoryId: "cat-2",
    imageHint: "EM",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 6,
    velocity30d: 0.8,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 10.2,
    consignmentPriceIdr: 392000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-6",
    sku: "LNY-GEM-IW-G",
    name: "Iron Will Bracelet | Gold | Lunar New Year Edition",
    categoryId: "cat-3",
    imageHint: "IW",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 4,
    velocity30d: 0.2,
    wholesaleActive: false,
    consignmentActive: true,
    wholesalePriceEur: 7.9,
    consignmentPriceIdr: 310000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-7",
    sku: "LNY-GEM-IW-S",
    name: "Iron Will Bracelet | Silver | Lunar New Year Edition",
    categoryId: "cat-3",
    imageHint: "IS",
    currentStock: { indira: 0, mita: 0, warehouse: 11 },
    lowStockThreshold: 4,
    velocity30d: 0.5,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 8.2,
    consignmentPriceIdr: 318000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-8",
    sku: "RE-GEM-LAL-Q",
    name: "Laylat al-Qadr Bracelet | Gold | Ramadhan Edition",
    categoryId: "cat-2",
    imageHint: "LQ",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 5,
    velocity30d: 1.1,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 9.1,
    consignmentPriceIdr: 356000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-9",
    sku: "GAL-MON-LUNE-G",
    name: "Moon Lunar Eclipse Bracelet | Gold",
    categoryId: "cat-4",
    imageHint: "ML",
    currentStock: { indira: 0, mita: 0, warehouse: 23 },
    lowStockThreshold: 8,
    velocity30d: 1.4,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 11.4,
    consignmentPriceIdr: 405000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-10",
    sku: "RE-GEM-NI-G",
    name: "Noor Iftar Bracelet | Gold | Ramadhan Edition",
    categoryId: "cat-2",
    imageHint: "NI",
    currentStock: { indira: 0, mita: 1, warehouse: 0 },
    lowStockThreshold: 6,
    velocity30d: 2.2,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 10.8,
    consignmentPriceIdr: 398000,
    updatedAt: defaultLastSyncedAt,
  }
];

export const defaultBatches: ProductionBatch[] = [
  {
    id: "incoming-1",
    name: "Indira Ramadan Return",
    status: "draft",
    source: "indira",
    notes: "Craftsman is preparing the first return shipment.",
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: defaultLastSyncedAt,
    createdBy: "Production Lead",
    items: [
      { id: "incoming-item-1", productId: "prd-5", quantity: 20 },
      { id: "incoming-item-2", productId: "prd-10", quantity: 12 },
    ],
    history: [
      {
        id: "incoming-1-history-1",
        kind: "created",
        title: "Created production batch",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-1-history-2",
        kind: "added",
        title: "Added Eid Mubarak Bracelet | Gold | Ramadhan Edition",
        detail: "+20 pcs • Source: Indira",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-1-history-3",
        kind: "added",
        title: "Added Noor Iftar Bracelet | Gold | Ramadhan Edition",
        detail: "+12 pcs • Source: Indira",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "incoming-2",
    name: "Mita Valentine Return",
    status: "submitted",
    source: "mita",
    notes: "Submitted by craftsman and waiting for internal verification.",
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: defaultLastSyncedAt,
    createdBy: "Production Lead",
    submittedAt: new Date(now.getTime() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { id: "incoming-item-3", productId: "prd-4", quantity: 5 },
      { id: "incoming-item-4", productId: "prd-8", quantity: 8 },
      {
        id: "incoming-item-4-custom",
        isCustom: true,
        customName: "Special heart clasp sample",
        note: "Craftsman packed this separately",
        quantity: 2,
      },
    ],
    history: [
      {
        id: "incoming-2-history-1",
        kind: "created",
        title: "Created production batch",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-2-history-2",
        kind: "added",
        title: "Added BABE Bracelet | Silver | Valentine's Day Edition",
        detail: "+5 pcs • Source: Mita",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-2-history-3",
        kind: "added",
        title: "Added Laylat al-Qadr Bracelet | Gold | Ramadhan Edition",
        detail: "+8 pcs • Source: Mita",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-2-history-4",
        kind: "completed",
        title: "Submitted production batch",
        detail: "Ready for internal verification",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "incoming-3",
    name: "Warehouse Mixed Return",
    status: "receiving",
    source: "warehouse",
    notes: "Internal team is checking a mixed craftsman return with custom lines.",
    createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: defaultLastSyncedAt,
    createdBy: "Admin",
    submittedAt: new Date(now.getTime() - 22 * 60 * 60 * 1000).toISOString(),
    receivingAt: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
    items: [
      { id: "incoming-item-5", productId: "prd-1", quantity: 9, checked: true },
      {
        id: "incoming-item-6",
        isCustom: true,
        customName: "Repair sample bracelet",
        note: "No SKU on the pouch",
        quantity: 3,
        checked: false,
      },
    ],
    history: [
      {
        id: "incoming-3-history-1",
        kind: "created",
        title: "Created production batch",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-3-history-2",
        kind: "added",
        title: "Added 4EVER Bracelet | Gold | Valentine's Day Edition",
        detail: "+9 pcs • Source: Warehouse",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 23.5 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-3-history-3",
        kind: "added",
        title: "Added Repair sample bracelet",
        detail: "+3 pcs • Source: Warehouse",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 23 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-3-history-4",
        kind: "completed",
        title: "Started receiving production batch",
        detail: "Checklist verification started",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
      },
    ],
  }
];

export const defaultProductionPlans: ProductionPlan[] = [
  {
    id: "dispatch-1",
    name: "Indira Dispatch Week 3",
    source: "indira",
    notes: "Outgoing bracelet bundle for craftsman handoff.",
    items: [
      { productId: "prd-1", plannedQty: 18, quantity: 18 },
      { productId: "prd-3", plannedQty: 10, quantity: 10 },
    ],
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "draft",
    history: [],
  },
];

export const defaultMovements: StockMovement[] = [];
