import type {
  Category,
  ProductionPlan,
  Preferences,
  Product,
  ProductionBatch,
  StockMovement,
  UserRole,
} from "@/lib/types";

const now = new Date("2026-04-15T09:40:54+08:00");

export const defaultPreferences: Preferences = {
  rowsPerPage: 10,
};

export const defaultRole: UserRole = "owner";

export const defaultLastSyncedAt = new Date(
  now.getTime() - 12 * 60 * 1000,
).toISOString();

export const defaultCategories: Category[] = [
  { id: "cat-1", name: "VALENTINE'S DAY EDITION", order: 0, createdAt: defaultLastSyncedAt },
  { id: "cat-2", name: "RAMADHAN EDITION", order: 1, createdAt: defaultLastSyncedAt },
  { id: "cat-3", name: "LUNAR NEW YEAR EDITION", order: 2, createdAt: defaultLastSyncedAt },
  { id: "cat-4", name: "GALAXY COLLECTION", order: 3, createdAt: defaultLastSyncedAt },
  { id: "cat-5", name: "CLASSIC ESSENTIALS", order: 4, createdAt: defaultLastSyncedAt },
  { id: "cat-6", name: "GEMSTONE GOLD COLLECTION", order: 5, createdAt: defaultLastSyncedAt },
  { id: "cat-7", name: "GEMSTONE SILVER COLLECTION", order: 6, createdAt: defaultLastSyncedAt },
  { id: "cat-8", name: "NUGGET KIDS COLLECTION", order: 7, createdAt: defaultLastSyncedAt },
  { id: "cat-9", name: "EMPOWERMENT COLLECTION", order: 8, createdAt: defaultLastSyncedAt },
  { id: "cat-10", name: "SHE IS - LIMITED EDITION COLLECTION", order: 9, createdAt: defaultLastSyncedAt },
  { id: "cat-11", name: "ANGEL COLLECTION", order: 10, createdAt: defaultLastSyncedAt },
  { id: "cat-12", name: "BEYOND COLLECTION", order: 11, createdAt: defaultLastSyncedAt },
  { id: "cat-13", name: "6MM GOLD COLLECTION", order: 12, createdAt: defaultLastSyncedAt },
  { id: "cat-14", name: "6MM SILVER COLLECTION", order: 13, createdAt: defaultLastSyncedAt },
  { id: "cat-15", name: "GEMSTONE HEART GOLD COLLECTION", order: 14, createdAt: defaultLastSyncedAt },
  { id: "cat-16", name: "GEMSTONE HEART SILVER COLLECTION", order: 15, createdAt: defaultLastSyncedAt },
  { id: "cat-17", name: "HEART KIDS COLLECTION", order: 16, createdAt: defaultLastSyncedAt },
  { id: "cat-18", name: "RINGS GOLD COLLECTION", order: 17, createdAt: defaultLastSyncedAt },
  { id: "cat-19", name: "RINGS SILVER COLLECTION", order: 18, createdAt: defaultLastSyncedAt },
  { id: "cat-20", name: "ZODIAC COLLECTION", order: 19, createdAt: defaultLastSyncedAt },
  { id: "cat-21", name: "FLOW & GLOW COLLECTION", order: 20, createdAt: defaultLastSyncedAt },
  { id: "cat-22", name: "GLOW COLLECTION", order: 21, createdAt: defaultLastSyncedAt },
  {
    id: "cat-23",
    name: "CELEBRATION OF LIFE - FRIENDSHIP AND TOGETHERNESS COLLECTION",
    order: 22,
    createdAt: defaultLastSyncedAt,
  },
  {
    id: "cat-24",
    name: "CELEBRATION OF LIFE - GROWTH AND MILESTONES COLLECTION",
    order: 23,
    createdAt: defaultLastSyncedAt,
  },
  {
    id: "cat-25",
    name: "CELEBRATION OF LIFE - PURE CELEBRATION COLLECTION",
    order: 24,
    createdAt: defaultLastSyncedAt,
  },
];

function makeProduct(input: {
  id: string;
  sku: string;
  name: string;
  categoryId: string;
  imageHint: string;
  indira?: number;
  mita?: number;
  warehouse?: number;
  lowStockThreshold?: number;
  wholesalePriceEur?: number;
  consignmentPriceIdr?: number;
}): Product {
  return {
    id: input.id,
    sku: input.sku,
    name: input.name,
    categoryId: input.categoryId,
    imageHint: input.imageHint,
    currentStock: {
      indira: input.indira ?? 0,
      mita: input.mita ?? 0,
      warehouse: input.warehouse ?? 0,
    },
    lowStockThreshold: input.lowStockThreshold ?? 5,
    velocity30d: 0.6,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: input.wholesalePriceEur ?? 9.9,
    consignmentPriceIdr: input.consignmentPriceIdr ?? 370000,
    updatedAt: defaultLastSyncedAt,
  };
}

export const defaultProducts: Product[] = [
  {
    id: "prd-1",
    sku: "VAL-GEM-4ER-G",
    name: "4EVER Bracelet | Gold | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "4V",
    currentStock: { indira: 2, mita: 0, warehouse: 17 },
    lowStockThreshold: 7,
    velocity30d: 1.2,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 9.9,
    consignmentPriceIdr: 370000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-2",
    sku: "VAL-GEM-4ER-S",
    name: "4EVER Bracelet | Silver | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "4S",
    currentStock: { indira: 0, mita: 0, warehouse: 11 },
    lowStockThreshold: 5,
    velocity30d: 0.4,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 8.8,
    consignmentPriceIdr: 342000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-3",
    sku: "VAL-GEM-B-G",
    name: "BABE Bracelet | Gold | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "BB",
    currentStock: { indira: 0, mita: 0, warehouse: 10 },
    lowStockThreshold: 5,
    velocity30d: 0.9,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 8.6,
    consignmentPriceIdr: 335000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-4",
    sku: "VAL-GEM-B-S",
    name: "BABE Bracelet | Silver | Valentine's Day Edition",
    categoryId: "cat-1",
    imageHint: "BS",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 5,
    velocity30d: 1.7,
    wholesaleActive: true,
    consignmentActive: false,
    wholesalePriceEur: 9.4,
    consignmentPriceIdr: 365000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-5",
    sku: "RE-GEM-EM-G",
    name: "Eid Mubarak Bracelet | Gold | Ramadhan Edition",
    categoryId: "cat-2",
    imageHint: "EM",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 6,
    velocity30d: 0.8,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 10.2,
    consignmentPriceIdr: 392000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-6",
    sku: "LNY-GEM-IW-G",
    name: "Iron Will Bracelet | Gold | Lunar New Year Edition",
    categoryId: "cat-3",
    imageHint: "IW",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 4,
    velocity30d: 0.2,
    wholesaleActive: false,
    consignmentActive: true,
    wholesalePriceEur: 7.9,
    consignmentPriceIdr: 310000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-7",
    sku: "LNY-GEM-IW-S",
    name: "Iron Will Bracelet | Silver | Lunar New Year Edition",
    categoryId: "cat-3",
    imageHint: "IS",
    currentStock: { indira: 0, mita: 0, warehouse: 11 },
    lowStockThreshold: 4,
    velocity30d: 0.5,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 8.2,
    consignmentPriceIdr: 318000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-8",
    sku: "RE-GEM-LAL-Q",
    name: "Laylat al-Qadr Bracelet | Gold | Ramadhan Edition",
    categoryId: "cat-2",
    imageHint: "LQ",
    currentStock: { indira: 0, mita: 0, warehouse: 0 },
    lowStockThreshold: 5,
    velocity30d: 1.1,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 9.1,
    consignmentPriceIdr: 356000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-9",
    sku: "GAL-MON-LUNE-G",
    name: "Moon Lunar Eclipse Bracelet | Gold",
    categoryId: "cat-4",
    imageHint: "ML",
    currentStock: { indira: 0, mita: 0, warehouse: 23 },
    lowStockThreshold: 8,
    velocity30d: 1.4,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 11.4,
    consignmentPriceIdr: 405000,
    updatedAt: defaultLastSyncedAt,
  },
  {
    id: "prd-10",
    sku: "RE-GEM-NI-G",
    name: "Noor Iftar Bracelet | Gold | Ramadhan Edition",
    categoryId: "cat-2",
    imageHint: "NI",
    currentStock: { indira: 0, mita: 1, warehouse: 0 },
    lowStockThreshold: 6,
    velocity30d: 2.2,
    wholesaleActive: true,
    consignmentActive: true,
    wholesalePriceEur: 10.8,
    consignmentPriceIdr: 398000,
    updatedAt: defaultLastSyncedAt,
  },
  makeProduct({
    id: "prd-11",
    sku: "YOG-CHA-NUG-MOO-G",
    name: "7 Chakras Moonstone Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "7G",
    warehouse: 18,
  }),
  makeProduct({
    id: "prd-12",
    sku: "YOG-CHA-NUG-MOO-S",
    name: "7 Chakras Moonstone Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "7S",
    indira: 10,
    warehouse: 3,
  }),
  makeProduct({
    id: "prd-13",
    sku: "YOG-CHA-NUG-KID-G",
    name: "7 Chakras Moonstone Nugget Kids Bracelet | Gold",
    categoryId: "cat-8",
    imageHint: "7K",
    warehouse: 13,
  }),
  makeProduct({
    id: "prd-14",
    sku: "EMP-ACC-CHO-S",
    name: "Accepting Choker | Silver",
    categoryId: "cat-9",
    imageHint: "AC",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-15",
    sku: "EMP-ADV-G",
    name: "Adventurous Bracelet | Gold",
    categoryId: "cat-9",
    imageHint: "AD",
    warehouse: 1,
  }),
  makeProduct({
    id: "prd-16",
    sku: "EMP-ADV-S",
    name: "Adventurous Bracelet | Silver",
    categoryId: "cat-9",
    imageHint: "AS",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-17",
    sku: "GEM-AFTU-G",
    name: "African Turquoise Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AG",
    warehouse: 9,
  }),
  makeProduct({
    id: "prd-18",
    sku: "GEM-AFTU-S",
    name: "African Turquoise Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "AS",
    indira: 5,
    warehouse: 7,
  }),
  makeProduct({
    id: "prd-19",
    sku: "EMP-ALD-S",
    name: "Aligned Bracelet | Silver",
    categoryId: "cat-10",
    imageHint: "AL",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-20",
    sku: "EMP-ALD-G",
    name: "Aligned Bracelet | Gold",
    categoryId: "cat-10",
    imageHint: "AG",
    mita: 2,
    warehouse: 7,
  }),
  makeProduct({
    id: "prd-21",
    sku: "AUR-AL-AN222-G",
    name: "Alignment Angel No. 222 Bracelet | Gold",
    categoryId: "cat-11",
    imageHint: "22",
    warehouse: 24,
  }),
  makeProduct({
    id: "prd-22",
    sku: "GEM-ALM-G",
    name: "Almandine Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AM",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-23",
    sku: "GEM-ATN-G",
    name: "Amatrine Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AT",
    warehouse: 1,
  }),
  makeProduct({
    id: "prd-24",
    sku: "6MM-GEM-AMA-G",
    name: "Amazonite 6mm Bracelet | Gold",
    categoryId: "cat-13",
    imageHint: "A6",
    warehouse: 13,
  }),
  makeProduct({
    id: "prd-25",
    sku: "6MM-GEM-AMA-S",
    name: "Amazonite 6mm Bracelet | Silver",
    categoryId: "cat-14",
    imageHint: "A6",
    warehouse: 1,
  }),
  makeProduct({
    id: "prd-26",
    sku: "GEM-AMA2-G",
    name: "Amazonite from South Africa Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AZ",
    warehouse: 39,
  }),
  makeProduct({
    id: "prd-27",
    sku: "GEM-AMA2-S",
    name: "Amazonite from South Africa Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "AZ",
    warehouse: 13,
  }),
  makeProduct({
    id: "prd-28",
    sku: "GEM-AMA-HEA-G",
    name: "Amazonite from South Africa Heart Bracelet | Gold",
    categoryId: "cat-15",
    imageHint: "AH",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-29",
    sku: "KID-GEM-AMA-HEA-G",
    name: "Amazonite from South Africa Heart Kids Bracelet | Gold",
    categoryId: "cat-17",
    imageHint: "AH",
    warehouse: 9,
  }),
  makeProduct({
    id: "prd-30",
    sku: "KID-GEM-AMA-NUG-G",
    name: "Amazonite from South Africa Nugget Kids Bracelet | Gold",
    categoryId: "cat-8",
    imageHint: "AN",
    warehouse: 8,
  }),
  makeProduct({
    id: "prd-31",
    sku: "6MM-GEM-AME2-G",
    name: "Amethyst 6mm Bracelet | Gold",
    categoryId: "cat-13",
    imageHint: "AM",
    warehouse: 1,
  }),
  makeProduct({
    id: "prd-32",
    sku: "6MM-GEM-AME2-S",
    name: "Amethyst 6mm Bracelet | Silver",
    categoryId: "cat-14",
    imageHint: "AM",
    warehouse: 1,
  }),
  makeProduct({
    id: "prd-33",
    sku: "GEM-AME2-G",
    name: "Amethyst Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AB",
    indira: 27,
    warehouse: 22,
  }),
  makeProduct({
    id: "prd-34",
    sku: "GEM-AME-S",
    name: "Amethyst Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "AB",
    indira: 6,
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-35",
    sku: "GEM-AME-HEA-G",
    name: "Amethyst Heart Bracelet | Gold",
    categoryId: "cat-15",
    imageHint: "AH",
    indira: 10,
    warehouse: 1,
  }),
  makeProduct({
    id: "prd-36",
    sku: "GEM-AME2-HEA-S",
    name: "Amethyst Heart Bracelet | Silver",
    categoryId: "cat-16",
    imageHint: "AH",
    indira: 5,
    warehouse: 3,
  }),
  makeProduct({
    id: "prd-37",
    sku: "KID-GEM-AME2-HEA-G",
    name: "Amethyst Heart Kids Bracelet | Gold",
    categoryId: "cat-17",
    imageHint: "AH",
    warehouse: 5,
  }),
  makeProduct({
    id: "prd-38",
    sku: "KID-GEM-AME2-NUG-G",
    name: "Amethyst Nugget Kids Bracelet | Gold",
    categoryId: "cat-8",
    imageHint: "AN",
    warehouse: 3,
  }),
  makeProduct({
    id: "prd-39",
    sku: "RIN-AME-G",
    name: "Amethyst Rings | Gold",
    categoryId: "cat-18",
    imageHint: "RG",
    warehouse: 5,
  }),
  makeProduct({
    id: "prd-40",
    sku: "RIN-AME-S",
    name: "Amethyst Rings | Silver",
    categoryId: "cat-19",
    imageHint: "RS",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-41",
    sku: "6MM-GEM-AGL-G",
    name: "Angelita 6mm Bracelet | Gold",
    categoryId: "cat-13",
    imageHint: "AN",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-42",
    sku: "6MM-GEM-APA-G",
    name: "Apatite 6mm Bracelet | Gold",
    categoryId: "cat-13",
    imageHint: "AP",
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-43",
    sku: "GEM-APA2-G",
    name: "Apatite Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AP",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-44",
    sku: "GEM-AQU-G",
    name: "Aquamarine from Brazil Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AQ",
    warehouse: 17,
  }),
  makeProduct({
    id: "prd-45",
    sku: "GEM-AQU-S",
    name: "Aquamarine from Brazil Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "AQ",
    indira: 11,
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-46",
    sku: "GEM-AQU-HEA-G",
    name: "Aquamarine from Brazil Heart Bracelet | Gold",
    categoryId: "cat-15",
    imageHint: "AQ",
    warehouse: 7,
  }),
  makeProduct({
    id: "prd-47",
    sku: "GEM-AQU3-G",
    name: "Aquamarine from Mozambique Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "AQ",
    warehouse: 5,
  }),
  makeProduct({
    id: "prd-48",
    sku: "ZOD-AQU-FEB",
    name: "Aquarius February Bracelet | Gold",
    categoryId: "cat-20",
    imageHint: "AF",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-49",
    sku: "ZOD-AQU-JAN",
    name: "Aquarius January Bracelet | Gold",
    categoryId: "cat-20",
    imageHint: "AJ",
    warehouse: 8,
  }),
  makeProduct({
    id: "prd-50",
    sku: "ZOD-ARI-APR",
    name: "Aries April Bracelet | Gold",
    categoryId: "cat-20",
    imageHint: "AA",
    indira: 10,
  }),
  makeProduct({
    id: "prd-51",
    sku: "ZOD-ARI-MAR",
    name: "Aries March Bracelet | Gold",
    categoryId: "cat-20",
    imageHint: "AM",
    warehouse: 3,
  }),
  makeProduct({
    id: "prd-52",
    sku: "FG-AF-G",
    name: "Aura Flow Bracelet | Gold",
    categoryId: "cat-21",
    imageHint: "AF",
    mita: 4,
  }),
  makeProduct({
    id: "prd-53",
    sku: "FG-AF-S",
    name: "Aura Flow Bracelet | Silver",
    categoryId: "cat-21",
    imageHint: "AF",
    mita: 4,
    warehouse: 2,
  }),
  makeProduct({
    id: "prd-54",
    sku: "EMP-AUTH-CHO-S",
    name: "Authentic Choker | Silver",
    categoryId: "cat-9",
    imageHint: "AU",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-55",
    sku: "AUR-BAL-AN888-G",
    name: "Balance Angel No. 888 Bracelet | Gold",
    categoryId: "cat-11",
    imageHint: "88",
    warehouse: 22,
  }),
  makeProduct({
    id: "prd-56",
    sku: "EMP-BTY-G",
    name: "Beautiful Bracelet | Gold",
    categoryId: "cat-12",
    imageHint: "BE",
    indira: 10,
    warehouse: 7,
  }),
  makeProduct({
    id: "prd-57",
    sku: "EMP-BTY-S",
    name: "Beautiful Bracelet | Silver",
    categoryId: "cat-12",
    imageHint: "BE",
    indira: 10,
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-58",
    sku: "GEM-BBWT-G",
    name: "Black Botswana Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BB",
    warehouse: 7,
  }),
  makeProduct({
    id: "prd-59",
    sku: "GEM-BBWS-S",
    name: "Black Botswana Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BB",
    warehouse: 13,
  }),
  makeProduct({
    id: "prd-60",
    sku: "6MM-BON-G",
    name: "Black Onyx 6mm Bracelet | Gold",
    categoryId: "cat-13",
    imageHint: "BO",
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-61",
    sku: "6MM-BON-S",
    name: "Black Onyx 6mm Bracelet | Silver",
    categoryId: "cat-14",
    imageHint: "BO",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-62",
    sku: "GEM-BLQ-G",
    name: "Black Rutilated Quartz Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BQ",
    warehouse: 21,
  }),
  makeProduct({
    id: "prd-63",
    sku: "GEM-BLQ-S",
    name: "Black Rutilated Quartz Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BQ",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-64",
    sku: "KID-GEM-BLQ-HEA-G",
    name: "Black Rutilated Quartz Heart Kids Bracelet | Gold",
    categoryId: "cat-17",
    imageHint: "BQ",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-65",
    sku: "KID-GEM-BLQ-NUG-G",
    name: "Black Rutilated Quartz Nugget Kids Bracelet | Gold",
    categoryId: "cat-8",
    imageHint: "BQ",
    indira: 3,
    warehouse: 6,
  }),
  makeProduct({
    id: "prd-66",
    sku: "GEM-BLA-G",
    name: "Black Spinel Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BS",
    indira: 20,
    mita: 3,
    warehouse: 2,
  }),
  makeProduct({
    id: "prd-67",
    sku: "GEM-BLA-S",
    name: "Black Spinel Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BS",
    indira: 11,
    warehouse: 8,
  }),
  makeProduct({
    id: "prd-68",
    sku: "GEM-BLA-HEA-G",
    name: "Black Spinel Heart Bracelet | Gold",
    categoryId: "cat-15",
    imageHint: "BH",
    warehouse: 13,
  }),
  makeProduct({
    id: "prd-69",
    sku: "GEM-BLA-HEA-S",
    name: "Black Spinel Heart Bracelet | Silver",
    categoryId: "cat-16",
    imageHint: "BH",
    warehouse: 9,
  }),
  makeProduct({
    id: "prd-70",
    sku: "KID-GEM-BLA-HEA-G",
    name: "Black Spinel Heart Kids Bracelet | Gold",
    categoryId: "cat-17",
    imageHint: "BH",
    warehouse: 14,
  }),
  makeProduct({
    id: "prd-71",
    sku: "KID-GEM-BLA-NUG-G",
    name: "Black Spinel Nugget Kids Bracelet | Gold",
    categoryId: "cat-8",
    imageHint: "BN",
    indira: 15,
    warehouse: 2,
  }),
  makeProduct({
    id: "prd-72",
    sku: "RIN-BLS-G",
    name: "Black Spinel Rings | Gold",
    categoryId: "cat-18",
    imageHint: "BR",
    warehouse: 6,
  }),
  makeProduct({
    id: "prd-73",
    sku: "RIN-BLS-S",
    name: "Black Spinel Rings | Silver",
    categoryId: "cat-19",
    imageHint: "BR",
    warehouse: 9,
  }),
  makeProduct({
    id: "prd-74",
    sku: "GEM-BT-G",
    name: "Black Tourmaline Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BT",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-75",
    sku: "GEM-BT-S",
    name: "Black Tourmaline Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BT",
    warehouse: 2,
  }),
  makeProduct({
    id: "prd-76",
    sku: "GEM-BLO-G",
    name: "Bloodstone Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BL",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-77",
    sku: "GEM-BLO-S",
    name: "Bloodstone Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BL",
    warehouse: 13,
  }),
  makeProduct({
    id: "prd-78",
    sku: "EMP-BL-G",
    name: "Bloom Bracelet | Gold",
    categoryId: "cat-22",
    imageHint: "BM",
    warehouse: 1,
  }),
  makeProduct({
    id: "prd-79",
    sku: "EMP-BL-S",
    name: "Bloom Bracelet | Silver",
    categoryId: "cat-22",
    imageHint: "BM",
    indira: 24,
  }),
  makeProduct({
    id: "prd-80",
    sku: "GEM-BCHAL-G",
    name: "Blue Chalcedony Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BC",
    warehouse: 2,
  }),
  makeProduct({
    id: "prd-81",
    sku: "GEM-BCHAL-S",
    name: "Blue Chalcedony Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BC",
    warehouse: 3,
  }),
  makeProduct({
    id: "prd-82",
    sku: "GEM-BL-G",
    name: "Blue Lace Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BL",
    warehouse: 16,
  }),
  makeProduct({
    id: "prd-83",
    sku: "GEM-BL-S",
    name: "Blue Lace Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BL",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-84",
    sku: "GEM-BSN-G",
    name: "Blue Sandstone Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BD",
    warehouse: 24,
  }),
  makeProduct({
    id: "prd-85",
    sku: "GEM-BSN-S",
    name: "Blue Sandstone Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BD",
    warehouse: 9,
  }),
  makeProduct({
    id: "prd-86",
    sku: "GEM-BSD-G",
    name: "Blue Sodalite Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BD",
    indira: 5,
    mita: 5,
    warehouse: 38,
  }),
  makeProduct({
    id: "prd-87",
    sku: "GEM-BSD-S",
    name: "Blue Sodalite Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BD",
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-88",
    sku: "GEM-BSAP-S",
    name: "Blue Sapphire Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BS",
    lowStockThreshold: 3,
  }),
  makeProduct({
    id: "prd-89",
    sku: "GEM-BLSP-G",
    name: "Blue Spinel Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BS",
    mita: 4,
    warehouse: 25,
  }),
  makeProduct({
    id: "prd-90",
    sku: "GEM-BLSP-S",
    name: "Blue Spinel Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BS",
    indira: 10,
  }),
  makeProduct({
    id: "prd-91",
    sku: "GEM-BLSP-HEA-G",
    name: "Blue Spinel Heart Bracelet | Gold",
    categoryId: "cat-15",
    imageHint: "BH",
    warehouse: 12,
  }),
  makeProduct({
    id: "prd-92",
    sku: "GEM-BLSP-HEA-S",
    name: "Blue Spinel Heart Bracelet | Silver",
    categoryId: "cat-16",
    imageHint: "BH",
    warehouse: 2,
  }),
  makeProduct({
    id: "prd-93",
    sku: "RIN-BLSP-G",
    name: "Blue Spinel Rings | Gold",
    categoryId: "cat-18",
    imageHint: "BR",
    warehouse: 30,
  }),
  makeProduct({
    id: "prd-94",
    sku: "RIN-BLSP-S",
    name: "Blue Spinel Rings | Silver",
    categoryId: "cat-19",
    imageHint: "BR",
    warehouse: 20,
  }),
  makeProduct({
    id: "prd-95",
    sku: "6MM-GEM-BTE-G",
    name: "Blue Tiger Eye 6mm Bracelet | Gold",
    categoryId: "cat-13",
    imageHint: "BT",
    warehouse: 10,
  }),
  makeProduct({
    id: "prd-96",
    sku: "GEM-BT2-G",
    name: "Blue Topaz Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BT",
    indira: 12,
    mita: 4,
    warehouse: 5,
  }),
  makeProduct({
    id: "prd-97",
    sku: "GEM-BT2-S",
    name: "Blue Topaz Bracelet | Silver",
    categoryId: "cat-7",
    imageHint: "BT",
    indira: 11,
    warehouse: 5,
  }),
  makeProduct({
    id: "prd-98",
    sku: "COL-BH-G",
    name: "Bonded Hearts Bracelet | Gold",
    categoryId: "cat-23",
    imageHint: "BH",
    mita: 6,
    warehouse: 9,
  }),
  makeProduct({
    id: "prd-99",
    sku: "COL-BH-S",
    name: "Bonded Hearts Bracelet | Silver",
    categoryId: "cat-23",
    imageHint: "BH",
    warehouse: 6,
  }),
  makeProduct({
    id: "prd-100",
    sku: "GEM-BOT2-G",
    name: "Botswana Agate Bracelet | Gold",
    categoryId: "cat-6",
    imageHint: "BA",
    warehouse: 7,
  }),
  makeProduct({
    id: "prd-101",
    sku: "EMP-BRA-G",
    name: "Bravery Bracelet | Gold",
    categoryId: "cat-9",
    imageHint: "BV",
    indira: 12,
    warehouse: 5,
  }),
  makeProduct({
    id: "prd-102",
    sku: "EMP-BRA-S",
    name: "Bravery Bracelet | Silver",
    categoryId: "cat-9",
    imageHint: "BV",
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-103",
    sku: "COL-BT-G",
    name: "Breakthrough Bracelet | Gold",
    categoryId: "cat-24",
    imageHint: "BK",
    indira: 12,
    warehouse: 6,
  }),
  makeProduct({
    id: "prd-104",
    sku: "COL-BT-S",
    name: "Breakthrough Bracelet | Silver",
    categoryId: "cat-24",
    imageHint: "BK",
    warehouse: 21,
  }),
  makeProduct({
    id: "prd-105",
    sku: "EMP-BSL-G",
    name: "Bright Soul Bracelet | Gold",
    categoryId: "cat-22",
    imageHint: "BS",
    warehouse: 8,
  }),
  makeProduct({
    id: "prd-106",
    sku: "COL-BLM-G",
    name: "Brilliant Moment Bracelet | Gold",
    categoryId: "cat-25",
    imageHint: "BM",
    warehouse: 9,
  }),
  makeProduct({
    id: "prd-107",
    sku: "COL-BLM-S",
    name: "Brilliant Moment Bracelet | Silver",
    categoryId: "cat-25",
    imageHint: "BM",
    warehouse: 4,
  }),
  makeProduct({
    id: "prd-108",
    sku: "6MM-GEM-BJSP-G",
    name: "Brown Jasper 6mm Bracelet | Gold",
    categoryId: "cat-13",
    imageHint: "BJ",
    warehouse: 10,
  })
];

export const defaultBatches: ProductionBatch[] = [
  {
    id: "incoming-1",
    name: "Indira Ramadan Return",
    status: "draft",
    source: "indira",
    notes: "Craftsman is preparing the first return shipment.",
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: defaultLastSyncedAt,
    createdBy: "Production Lead",
    items: [
      { id: "incoming-item-1", productId: "prd-5", quantity: 20 },
      { id: "incoming-item-2", productId: "prd-10", quantity: 12 },
    ],
    history: [
      {
        id: "incoming-1-history-1",
        kind: "created",
        title: "Created production batch",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-1-history-2",
        kind: "added",
        title: "Added Eid Mubarak Bracelet | Gold | Ramadhan Edition",
        detail: "+20 pcs • Source: Indira",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-1-history-3",
        kind: "added",
        title: "Added Noor Iftar Bracelet | Gold | Ramadhan Edition",
        detail: "+12 pcs • Source: Indira",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "incoming-2",
    name: "Mita Valentine Return",
    status: "submitted",
    source: "mita",
    notes: "Submitted by craftsman and waiting for internal verification.",
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: defaultLastSyncedAt,
    createdBy: "Production Lead",
    submittedAt: new Date(now.getTime() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { id: "incoming-item-3", productId: "prd-4", quantity: 5 },
      { id: "incoming-item-4", productId: "prd-8", quantity: 8 },
      {
        id: "incoming-item-4-custom",
        isCustom: true,
        customName: "Special heart clasp sample",
        note: "Craftsman packed this separately",
        quantity: 2,
      },
    ],
    history: [
      {
        id: "incoming-2-history-1",
        kind: "created",
        title: "Created production batch",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-2-history-2",
        kind: "added",
        title: "Added BABE Bracelet | Silver | Valentine's Day Edition",
        detail: "+5 pcs • Source: Mita",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-2-history-3",
        kind: "added",
        title: "Added Laylat al-Qadr Bracelet | Gold | Ramadhan Edition",
        detail: "+8 pcs • Source: Mita",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-2-history-4",
        kind: "completed",
        title: "Submitted production batch",
        detail: "Ready for internal verification",
        actor: "Production Lead",
        createdAt: new Date(now.getTime() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "incoming-3",
    name: "Warehouse Mixed Return",
    status: "receiving",
    source: "warehouse",
    notes: "Internal team is checking a mixed craftsman return with custom lines.",
    createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: defaultLastSyncedAt,
    createdBy: "Admin",
    submittedAt: new Date(now.getTime() - 22 * 60 * 60 * 1000).toISOString(),
    receivingAt: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
    items: [
      { id: "incoming-item-5", productId: "prd-1", quantity: 9, checked: true },
      {
        id: "incoming-item-6",
        isCustom: true,
        customName: "Repair sample bracelet",
        note: "No SKU on the pouch",
        quantity: 3,
        checked: false,
      },
    ],
    history: [
      {
        id: "incoming-3-history-1",
        kind: "created",
        title: "Created production batch",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-3-history-2",
        kind: "added",
        title: "Added 4EVER Bracelet | Gold | Valentine's Day Edition",
        detail: "+9 pcs • Source: Warehouse",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 23.5 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-3-history-3",
        kind: "added",
        title: "Added Repair sample bracelet",
        detail: "+3 pcs • Source: Warehouse",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 23 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "incoming-3-history-4",
        kind: "completed",
        title: "Started receiving production batch",
        detail: "Checklist verification started",
        actor: "Admin",
        createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
      },
    ],
  }
];

export const defaultProductionPlans: ProductionPlan[] = [
  {
    id: "dispatch-1",
    name: "Indira Dispatch Week 3",
    source: "indira",
    notes: "Outgoing bracelet bundle for craftsman handoff.",
    items: [
      { productId: "prd-1", plannedQty: 18, quantity: 18 },
      { productId: "prd-3", plannedQty: 10, quantity: 10 },
    ],
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "draft",
    history: [],
  },
];

export const defaultMovements: StockMovement[] = [];
